/property:Configuration=Windows /property:Platform=x86
########################################################
##               MASTER                               ##
########################################################
-
  branches:
    only:
      - master

  image: 
    - Visual Studio 2019
  configuration: Default
  platform: Default
  version: 13.0.0.{build}
  clone_depth: 1
  
  skip_commits:
    files:
      - docs/*
      - LICENSE
      - README.md
      - .travis.yml
      - codecov.yml
      - .gitignore
      
  cache:
    - packages -> **\packages.config, **\*.csproj, build.ps1 #local nuget folder
#    - '%HOMEDRIVE%%HOMEPATH%\.nuget\packages -> **\packages.config, **\*.csproj, build.ps1' #global nuget folder
    - '%LocalAppData%\Microsoft\dotnet -> appveyor.yml'
    - '$HOME/.local/share/NuGet/v3-cache' #nuget cache ubuntu
    - '$HOME/.local/share/NuGet/Cache' #nuget cache ubuntu
    - '%LocalAppData%\NuGet\Cache' #v>3 nuget cache windows
    - '%LocalAppData%\NuGet\v3-cache' #nuget cache windows

  assembly_info:
    patch: true
    file: Standalone\Properties\AssemblyInfo.cs
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}"
           
  install:
    - ps: ./init_script.ps1
    - git submodule update --init --recursive

  build_script:
    - ps: ./build_script.ps1

  after_test:
    - ps: ./after_test_nuget.ps1

  deploy:
    - provider: NuGet
      server: https://nuget.pkg.github.com/FactrIDE/index.json
      artifact: Steamworks.NET-Standalone.nupkg
      username: FactrIDE
      api_key:
        secure: Cc5LQq7vuBMi2CTmoYPLFHuXeFeqTThn6xbL9O/f+r4GAut49B7rDBKfzbwl2TtC
      on:
        os: Windows_NT
        configuration: Release
        APPVEYOR_REPO_TAG: true